Section 1:
This first section will contain the import of the Sports Dataset.

My goal in this project is to see which skills have a higher correlation to win percentage.

Considering the stats are based on hockey, one example question would be; Does a higher faceoff win ratio correlate to a higher game win percentage? Or, is there a specific coach that leads to a higher win percentage?

In [ ]:
# Importing the necessary Python Packages
import pandas as pd
import matplotlib as plt
import sklearn as sk

Section 2: Importing the Dataset and doing initial analysis

Inclusive of:
- Initial Data View
- Dataframe Shapen and Column Index
- Dataframe Column Datatypes
- Column missing values

In [ ]:
# Dataset Import / Initial Dataframe view
game_stats_df = pd.read_csv('game_stats_v2.csv')
game_stats_df.head(5)

,game_id,date_time_GMT,home_team,away_team,home_won,home_settled_in,home_head_coach,home_goals,home_shots,home_hits,...,away_goals,away_shots,away_hits,away_pim,away_powerPlayOpportunities,away_powerPlayGoals,away_faceOffWinPercentage,away_giveaways,away_takeaways,away_blocked
0,2016020045,2016-10-19T00:30:00Z,Chicago Blackhawks,Philadelphia Flyers,True,REG,Joel Quenneville,7.0,28.0,20.0,...,4.0,27.0,30.0,6.0,4.0,2.0,50.9,12.0,9.0,11.0
1,2017020812,2018-02-07T00:00:00Z,Buffalo Sabres,Anaheim Ducks,False,OT,Phil Housley,3.0,33.0,17.0,...,4.0,34.0,16.0,6.0,3.0,1.0,43.8,7.0,4.0,14.0
2,2015020314,2015-11-24T01:00:00Z,Winnipeg Jets,Colorado Avalanche,False,REG,Paul Maurice,1.0,21.0,22.0,...,4.0,29.0,17.0,9.0,3.0,1.0,45.7,13.0,5.0,20.0
3,2015020849,2016-02-17T00:00:00Z,Carolina Hurricanes,Winnipeg Jets,True,REG,Bill Peters,2.0,29.0,16.0,...,1.0,21.0,21.0,10.0,4.0,0.0,31.4,4.0,14.0,16.0
4,2017020586,2017-12-30T03:00:00Z,Anaheim Ducks,Calgary Flames,True,REG,Randy Carlyle,2.0,41.0,15.0,...,1.0,23.0,20.0,19.0,3.0,0.0,54.7,10.0,4.0,7.0

In [ ]:
# Dataframe size and full column name index
print(game_stats_df.shape)
print(game_stats_df.columns)

(23735, 30)
Index(['game_id', 'date_time_GMT', 'home_team', 'away_team', 'home_won',
       'home_settled_in', 'home_head_coach', 'home_goals', 'home_shots',
       'home_hits', 'home_pim', 'home_powerPlayOpportunities',
       'home_powerPlayGoals', 'home_faceOffWinPercentage', 'home_giveaways',
       'home_takeaways', 'home_blocked', 'away_won', 'away_settled_in',
       'away_head_coach', 'away_goals', 'away_shots', 'away_hits', 'away_pim',
       'away_powerPlayOpportunities', 'away_powerPlayGoals',
       'away_faceOffWinPercentage', 'away_giveaways', 'away_takeaways',
       'away_blocked'],
      dtype='object')

In [ ]:
# Column Datatypes
game_stats_df.dtypes

game_id                          int64
date_time_GMT                   object
home_team                       object
away_team                       object
home_won                          bool
home_settled_in                 object
home_head_coach                 object
home_goals                     float64
home_shots                     float64
home_hits                      float64
home_pim                       float64
home_powerPlayOpportunities    float64
home_powerPlayGoals            float64
home_faceOffWinPercentage      float64
home_giveaways                 float64
home_takeaways                 float64
home_blocked                   float64
away_won                          bool
away_settled_in                 object
away_head_coach                 object
away_goals                     float64
away_shots                     float64
away_hits                      float64
away_pim                       float64
away_powerPlayOpportunities    float64
away_powerPlayGoals            float64
away_faceOffWinPercentage      float64
away_giveaways                 float64
away_takeaways                 float64
away_blocked                   float64
dtype: object

In [ ]:
# Missing value analysis
game_stats_df.isna().sum()

game_id                            0
date_time_GMT                      0
home_team                          5
away_team                          5
home_won                           0
home_settled_in                    0
home_head_coach                   14
home_goals                         4
home_shots                         4
home_hits                       2464
home_pim                           4
home_powerPlayOpportunities        4
home_powerPlayGoals                4
home_faceOffWinPercentage      11074
home_giveaways                  2464
home_takeaways                  2464
home_blocked                    2464
away_won                           0
away_settled_in                    0
away_head_coach                   14
away_goals                         4
away_shots                         4
away_hits                       2464
away_pim                           4
away_powerPlayOpportunities        4
away_powerPlayGoals                4
away_faceOffWinPercentage      11074
away_giveaways                  2464
away_takeaways                  2464
away_blocked                    2464
dtype: int64

Section 3: Initial Data Cleaning

The two necessary steps to take relative to cleaning this data are the following:
- Column Rename, this is simply to ensure no columns have any spacing, and to turn column names lowercase for easier syntax
- Converting the date column to a Pandas Datetime format for the purposes of analyses over time periods

In [9]:
# Column clean up and check
game_stats_df.columns = game_stats_df.columns.str.lower().str.strip()
# game_stats_df.columns

# Date column conversion to Pandas Datetime format and check

game_stats_df['date_time_gmt'] = pd.to_datetime(game_stats_df['date_time_gmt'])
# game_stats_df['date_time_gmt']

Step 4: Descriptive Statistics and Categorical Summaries

In [19]:
# Selecting only numerical columns
game_stats_df_numeric = game_stats_df.select_dtypes('float64')

# Creating the descriptive statistics
# Note: These statistics are related to each game and are not specific to a team
game_stats_df_numeric.describe()

,home_goals,home_shots,home_hits,home_pim,home_powerplayopportunities,home_powerplaygoals,home_faceoffwinpercentage,home_giveaways,home_takeaways,home_blocked,away_goals,away_shots,away_hits,away_pim,away_powerplayopportunities,away_powerplaygoals,away_faceoffwinpercentage,away_giveaways,away_takeaways,away_blocked
count,23731.000000,23731.000000,21271.000000,23731.000000,23731.000000,23731.000000,12661.000000,21271.000000,21271.000000,21271.000000,23731.000000,23731.000000,21271.000000,23731.000000,23731.000000,23731.000000,12661.000000,21271.000000,21271.000000,21271.000000
mean,2.898909,30.656441,21.784636,11.743289,3.938730,0.732207,51.565192,10.013963,7.557191,12.920878,2.623235,28.888163,20.003573,12.483165,3.605242,0.620496,48.355833,7.274881,5.746462,13.496592
std,1.683219,6.905179,9.196252,9.051843,1.941158,0.851393,7.174364,5.725400,4.410752,5.559009,1.603703,6.744195,9.212713,9.360113,1.831065,0.780725,7.156689,4.859791,3.677398,5.700920
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,26.000000,16.000000,6.000000,3.000000,0.000000,46.900000,6.000000,4.000000,9.000000,1.000000,24.000000,14.000000,6.000000,2.000000,0.000000,43.600000,4.000000,3.000000,10.000000
50%,3.000000,30.000000,21.000000,10.000000,4.000000,1.000000,51.700000,9.000000,7.000000,13.000000,2.000000,29.000000,19.000000,10.000000,3.000000,0.000000,48.300000,7.000000,5.000000,13.000000
75%,4.000000,35.000000,27.000000,15.000000,5.000000,1.000000,56.400000,13.000000,10.000000,16.000000,4.000000,33.000000,25.000000,15.000000,5.000000,1.000000,53.100000,10.000000,8.000000,17.000000
max,12.000000,88.000000,80.000000,213.000000,15.000000,6.000000,79.200000,52.000000,40.000000,40.000000,11.000000,63.000000,80.000000,206.000000,16.000000,7.000000,76.200000,49.000000,37.000000,62.000000